CREATE USER 'uBlog' @'%' IDENTIFIED VIA mysql_native_password USING '***';

GRANT
SELECT
,
INSERT
,
UPDATE
,
    DELETE,
    CREATE,
    DROP,
    FILE,
    INDEX,
    ALTER,
    CREATE TEMPORARY TABLES,
    CREATE VIEW,
    EVENT,
    TRIGGER,
    SHOW VIEW,
    CREATE ROUTINE,
    ALTER ROUTINE,
    EXECUTE ON *.* TO 'uBlog' @'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;

CREATE DATABASE IF NOT EXISTS `uBlog`;

GRANT ALL PRIVILEGES ON `uBlog`.* TO 'uBlog' @'%';

GRANT ALL PRIVILEGES ON `uBlog\_%`.* TO 'uBlog' @'%';
